const fs = require('fs');
const file = 'src/newsCoreV2/summary/SummaryEngine.ts';
let content = fs.readFileSync(file, 'utf8');

if (content.includes('generateDeterministicSummarySync(article)')) {
  // We want to replace the body of generateSummary
  content = content.replace(
    /public static async generateSummary\(article: NewsArticleV2\): Promise<NewsSummary> \{\s*return this\.generateDeterministicSummarySync\(article\);\s*\}/s,
    `public static async generateSummary(article: NewsArticleV2): Promise<NewsSummary> {
    const intel = await UnifiedIntelligenceEngine.generateAIIntelligence(article);
    const deterministic = this.generateDeterministicSummarySync(article);
    
    // Merge
    return {
      ...deterministic,
      summary: intel.executiveSummary,
      whyItMatters: intel.whyItMatters,
      marketImpact: intel.marketImpact,
      riskWatchpoints: intel.risk,
      // determine if it's AI generated by checking version
      processingMode: intel.intelligenceVersion.includes("_AI") ? "AI_GROUNDED" : "DETERMINISTIC_FALLBACK"
    };
  }`
  );
  fs.writeFileSync(file, content, 'utf8');
  console.log('Patched SummaryEngine.ts');
} else {
  console.log('SummaryEngine already patched');
}
