/**
 * ATHENA — Phase 18 Event Taxonomy
 * MarketSurveillanceEventTypes.ts
 */

export enum MarketSurveillanceEventType {
  PRICE_ANOMALY = 'PRICE_ANOMALY',
  VOLUME_ANOMALY = 'VOLUME_ANOMALY',
  RVOL_SPIKE = 'RVOL_SPIKE',
  VWAP_DISPLACEMENT = 'VWAP_DISPLACEMENT',
  MOMENTUM_ACCELERATION = 'MOMENTUM_ACCELERATION',
  MOMENTUM_REVERSAL = 'MOMENTUM_REVERSAL',
  BREAKOUT = 'BREAKOUT',
  BREAKDOWN = 'BREAKDOWN',
  GAP_ANOMALY = 'GAP_ANOMALY',
  VOLATILITY_EXPANSION = 'VOLATILITY_EXPANSION',
  VOLATILITY_COMPRESSION = 'VOLATILITY_COMPRESSION',
  IV_SPIKE = 'IV_SPIKE',
  IV_CRUSH = 'IV_CRUSH',
  OI_BUILDUP = 'OI_BUILDUP',
  OI_UNWIND = 'OI_UNWIND',
  LONG_BUILDUP = 'LONG_BUILDUP',
  SHORT_BUILDUP = 'SHORT_BUILDUP',
  SHORT_COVERING = 'SHORT_COVERING',
  LONG_UNWINDING = 'LONG_UNWINDING',
  OPTION_CHAIN_ANOMALY = 'OPTION_CHAIN_ANOMALY',
  PUT_CALL_IMBALANCE = 'PUT_CALL_IMBALANCE',
  UNUSUAL_OPTIONS_ACTIVITY = 'UNUSUAL_OPTIONS_ACTIVITY',
  BASIS_ANOMALY = 'BASIS_ANOMALY',
  LIQUIDITY_SHOCK = 'LIQUIDITY_SHOCK',
  SPREAD_WIDENING = 'SPREAD_WIDENING',
  SECTOR_DIVERGENCE = 'SECTOR_DIVERGENCE',
  INDEX_DIVERGENCE = 'INDEX_DIVERGENCE',
  CONSTITUENT_DIVERGENCE = 'CONSTITUENT_DIVERGENCE',
  CROSS_ASSET_SHOCK = 'CROSS_ASSET_SHOCK',
  NEWS_MARKET_MISMATCH = 'NEWS_MARKET_MISMATCH',
  NEWS_WITHOUT_REACTION = 'NEWS_WITHOUT_REACTION',
  PRICE_WITHOUT_NEWS = 'PRICE_WITHOUT_NEWS',
  CORRELATED_ASSET_SHOCK = 'CORRELATED_ASSET_SHOCK',
  MARKET_REGIME_TRANSITION = 'MARKET_REGIME_TRANSITION',
  MULTI_FACTOR_ANOMALY = 'MULTI_FACTOR_ANOMALY'
}
