export interface CompanyMasterRecord {
  name: string;
  officialName?: string;
  symbol: string;
  scripCode?: string;
  isin?: string;
  cin?: string;
  website?: string;
  emailDomain?: string;
  sector: string;
  industry: string;
  marketCap?: 'Large Cap' | 'Mid Cap' | 'Small Cap';
  indices?: string[];
  fo: boolean;
  exchange?: string;
  country?: string;
  aliases: string[];
}

export class CompanyMasterDatabase {
  public static readonly MASTER_RECORDS: CompanyMasterRecord[] = [
    // F&O STOCKS (TOP PRIORITY - ALL 200 F&O STOCKS)
    {
      name: 'Kalyan Jewellers India Limited',
      officialName: 'Kalyan Jewellers India Limited',
      symbol: 'KALYANKJIL',
      scripCode: '543278',
      isin: 'INE303R01014',
      exchange: 'NSE',
      sector: 'Consumer Discretionary',
      industry: 'Jewellery',
      marketCap: 'Mid Cap',
      indices: ['Nifty Midcap 100', 'Nifty 500'],
      fo: true,
      country: 'India',
      aliases: ['Kalyan Jewellers', 'Kalyan', 'Kalyan Jewellers India', 'Kalyan Jewellers India Ltd', 'Kalyan Jeweller']
    },
    {
      name: 'Nestlé India Limited',
      officialName: 'Nestlé India Limited',
      symbol: 'NESTLEIND',
      scripCode: '500790',
      isin: 'INE239A01024',
      exchange: 'NSE',
      sector: 'Consumer Goods',
      industry: 'Packaged Foods',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty 100', 'Nifty FMCG'],
      fo: true,
      country: 'India',
      aliases: ['Nestle India', 'Nestle', 'Nestlé', 'Nestlé India', 'Nestle India Ltd', 'Nestlé India Ltd', 'Maggi']
    },
    {
      name: 'Bharti Airtel Limited',
      officialName: 'Bharti Airtel Limited',
      symbol: 'BHARTIARTL',
      scripCode: '532454',
      isin: 'INE397D01024',
      exchange: 'NSE',
      sector: 'Telecommunication',
      industry: 'Telecom Services',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['Bharti Airtel', 'Airtel', 'Bharti Airtel Ltd', 'Airtel India']
    },
    {
      name: 'Reliance Industries Limited',
      officialName: 'Reliance Industries Limited',
      symbol: 'RELIANCE',
      scripCode: '500325',
      isin: 'INE002A01018',
      exchange: 'NSE',
      sector: 'Energy',
      industry: 'Integrated Oil & Gas / Petrochemicals',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty 100', 'Nifty Energy'],
      fo: true,
      country: 'India',
      aliases: ['RIL', 'Reliance', 'Reliance Industries', 'Jio', 'Reliance Retail', 'Jio Platforms']
    },
    {
      name: 'Larsen & Toubro Limited',
      officialName: 'Larsen & Toubro Limited',
      symbol: 'LT',
      scripCode: '500510',
      isin: 'INE018A01030',
      exchange: 'NSE',
      sector: 'Capital Goods',
      industry: 'Engineering & Construction',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty 100', 'Nifty Infrastructure'],
      fo: true,
      country: 'India',
      aliases: ['L&T', 'LT', 'Larsen & Toubro', 'Larsen and Toubro', 'Larsen & Toubro Ltd', 'Larsen']
    },
    {
      name: 'Mahindra & Mahindra Limited',
      officialName: 'Mahindra & Mahindra Limited',
      symbol: 'M&M',
      scripCode: '500520',
      isin: 'INE101A01026',
      exchange: 'NSE',
      sector: 'Automobile',
      industry: 'Utility & Farm Equipment',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Auto'],
      fo: true,
      country: 'India',
      aliases: ['M&M', 'Mahindra & Mahindra', 'Mahindra', 'Mahindra and Mahindra', 'Mahindra & Mahindra Ltd', 'Mahindra Auto']
    },
    {
      name: 'Tata Motors Passenger Vehicles Ltd',
      officialName: 'Tata Motors Limited',
      symbol: 'TATAMOTORS',
      scripCode: '500570',
      isin: 'INE155A01022',
      exchange: 'NSE',
      sector: 'Automobile',
      industry: 'Passenger Vehicles & Electric Mobility',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Auto'],
      fo: true,
      country: 'India',
      aliases: ['Tata Motors', 'Tatamotors', 'JLR', 'Jaguar Land Rover', 'Tata Motors PV', 'Tata Motors Passenger Vehicles']
    },
    {
      name: 'Tata Consultancy Services Limited',
      officialName: 'Tata Consultancy Services Limited',
      symbol: 'TCS',
      scripCode: '532540',
      isin: 'INE467B01029',
      exchange: 'NSE',
      sector: 'Technology',
      industry: 'IT Services & Consulting',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty IT'],
      fo: true,
      country: 'India',
      aliases: ['TCS', 'Tata Consultancy', 'Tata Consultancy Services', 'Tata Consultancy Services Ltd']
    },
    {
      name: 'Infosys Limited',
      officialName: 'Infosys Limited',
      symbol: 'INFY',
      scripCode: '500209',
      isin: 'INE009A01021',
      exchange: 'NSE',
      sector: 'Technology',
      industry: 'IT Services',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty IT'],
      fo: true,
      country: 'India',
      aliases: ['Infosys', 'Infy', 'Infosys Ltd', 'Infosys Limited']
    },
    {
      name: 'HDFC Bank Limited',
      officialName: 'HDFC Bank Limited',
      symbol: 'HDFCBANK',
      scripCode: '500180',
      isin: 'INE040A01034',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Private Bank',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Bank'],
      fo: true,
      country: 'India',
      aliases: ['HDFC Bank', 'HDFCBank', 'HDFC Bank Ltd', 'HDFC']
    },
    {
      name: 'ICICI Bank Limited',
      officialName: 'ICICI Bank Limited',
      symbol: 'ICICIBANK',
      scripCode: '502150',
      isin: 'INE090A01021',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Private Bank',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Bank'],
      fo: true,
      country: 'India',
      aliases: ['ICICI Bank', 'ICICIBank', 'ICICI Bank Ltd', 'ICICI']
    },
    {
      name: 'State Bank of India',
      officialName: 'State Bank of India',
      symbol: 'SBIN',
      scripCode: '500112',
      isin: 'INE062A01020',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Public Bank',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Bank', 'Nifty PSU Bank'],
      fo: true,
      country: 'India',
      aliases: ['SBI', 'State Bank of India', 'State Bank', 'SBIN']
    },
    {
      name: 'Axis Bank Limited',
      officialName: 'Axis Bank Limited',
      symbol: 'AXISBANK',
      scripCode: '532215',
      isin: 'INE238A01034',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Private Bank',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Bank'],
      fo: true,
      country: 'India',
      aliases: ['Axis Bank', 'AxisBank', 'Axis Bank Ltd', 'Axis']
    },
    {
      name: 'Kotak Mahindra Bank Limited',
      officialName: 'Kotak Mahindra Bank Limited',
      symbol: 'KOTAKBANK',
      scripCode: '500247',
      isin: 'INE237A01028',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Private Bank',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Bank'],
      fo: true,
      country: 'India',
      aliases: ['Kotak Bank', 'KotakBank', 'Kotak Mahindra Bank', 'Kotak Mahindra', 'Kotak']
    },
    {
      name: 'IndusInd Bank Limited',
      officialName: 'IndusInd Bank Limited',
      symbol: 'INDUSINDBK',
      scripCode: '532187',
      isin: 'INE095A01012',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Private Bank',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Bank'],
      fo: true,
      country: 'India',
      aliases: ['IndusInd Bank', 'IndusInd', 'IndusIndBank', 'IndusInd Bank Ltd']
    },
    {
      name: 'Bharat Electronics Limited',
      officialName: 'Bharat Electronics Limited',
      symbol: 'BEL',
      scripCode: '500049',
      isin: 'INE263A01024',
      exchange: 'NSE',
      sector: 'Capital Goods',
      industry: 'Defence Electronics',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Defence'],
      fo: true,
      country: 'India',
      aliases: ['BEL', 'Bharat Electronics', 'Bharat Electronics Ltd', 'Bharat Electronics Limited']
    },
    {
      name: 'Hindustan Aeronautics Limited',
      officialName: 'Hindustan Aeronautics Limited',
      symbol: 'HAL',
      scripCode: '541154',
      isin: 'INE066F01020',
      exchange: 'NSE',
      sector: 'Capital Goods',
      industry: 'Aerospace & Defence',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Defence'],
      fo: true,
      country: 'India',
      aliases: ['HAL', 'Hindustan Aeronautics', 'Hindustan Aeronautics Ltd', 'Hindustan Aeronautics Limited']
    },
    {
      name: 'Bharat Dynamics Limited',
      officialName: 'Bharat Dynamics Limited',
      symbol: 'BDL',
      scripCode: '541143',
      isin: 'INE171Z01018',
      exchange: 'NSE',
      sector: 'Defence',
      industry: 'Aerospace & Defence',
      marketCap: 'Mid Cap',
      indices: ['Nifty Defence', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['BDL', 'Bharat Dynamics', 'Bharat Dynamics Ltd']
    },
    {
      name: 'Mazagon Dock Shipbuilders Limited',
      officialName: 'Mazagon Dock Shipbuilders Limited',
      symbol: 'MAZDOCK',
      scripCode: '543237',
      isin: 'INE249Z01012',
      exchange: 'NSE',
      sector: 'Capital Goods',
      industry: 'Shipbuilding',
      marketCap: 'Large Cap',
      indices: ['Nifty Defence', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Mazagon Dock', 'Mazagon Dock Shipbuilders', 'MDL', 'Mazagon']
    },
    {
      name: 'Cochin Shipyard Limited',
      officialName: 'Cochin Shipyard Limited',
      symbol: 'COCHINSHIP',
      scripCode: '540678',
      isin: 'INE704P01025',
      exchange: 'NSE',
      sector: 'Capital Goods',
      industry: 'Shipbuilding',
      marketCap: 'Mid Cap',
      indices: ['Nifty Defence', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Cochin Shipyard', 'CSL', 'Cochin Shipyard Ltd']
    },
    {
      name: 'Data Patterns (India) Limited',
      officialName: 'Data Patterns (India) Limited',
      symbol: 'DATAPATTNS',
      scripCode: '543428',
      isin: 'INE0IX101010',
      exchange: 'NSE',
      sector: 'Defence',
      industry: 'Defence Electronics',
      marketCap: 'Small Cap',
      indices: ['Nifty Defence', 'Nifty Smallcap 250'],
      fo: true,
      country: 'India',
      aliases: ['Data Patterns', 'Data Patterns India', 'Data Patterns (India) Ltd']
    },
    {
      name: 'Titan Company Limited',
      officialName: 'Titan Company Limited',
      symbol: 'TITAN',
      scripCode: '500114',
      isin: 'INE280A01028',
      exchange: 'NSE',
      sector: 'Consumer Discretionary',
      industry: 'Jewellery & Watches',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Consumer Durables'],
      fo: true,
      country: 'India',
      aliases: ['Titan', 'Titan Company', 'Titan Company Ltd', 'Tanishq']
    },
    {
      name: 'ITC Limited',
      officialName: 'ITC Limited',
      symbol: 'ITC',
      scripCode: '500875',
      isin: 'INE154A01025',
      exchange: 'NSE',
      sector: 'Consumer Goods',
      industry: 'Diversified FMCG',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty FMCG'],
      fo: true,
      country: 'India',
      aliases: ['ITC', 'ITC Ltd', 'ITC Limited']
    },
    {
      name: 'Wipro Limited',
      officialName: 'Wipro Limited',
      symbol: 'WIPRO',
      scripCode: '507685',
      isin: 'INE075A01022',
      exchange: 'NSE',
      sector: 'Technology',
      industry: 'IT Services',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty IT'],
      fo: true,
      country: 'India',
      aliases: ['Wipro', 'Wipro Ltd', 'Wipro Limited']
    },
    {
      name: 'HCL Technologies Limited',
      officialName: 'HCL Technologies Limited',
      symbol: 'HCLTECH',
      scripCode: '532281',
      isin: 'INE860A01027',
      exchange: 'NSE',
      sector: 'Technology',
      industry: 'IT Services',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty IT'],
      fo: true,
      country: 'India',
      aliases: ['HCL Tech', 'HCLTech', 'HCL Technologies', 'HCL Technologies Ltd']
    },
    {
      name: 'Tech Mahindra Limited',
      officialName: 'Tech Mahindra Limited',
      symbol: 'TECHM',
      scripCode: '532755',
      isin: 'INE669C01036',
      exchange: 'NSE',
      sector: 'Technology',
      industry: 'IT Services',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty IT'],
      fo: true,
      country: 'India',
      aliases: ['Tech Mahindra', 'TechM', 'Tech Mahindra Ltd']
    },
    {
      name: 'LTIMindtree Limited',
      officialName: 'LTIMindtree Limited',
      symbol: 'LTIM',
      scripCode: '540005',
      isin: 'INE214T01019',
      exchange: 'NSE',
      sector: 'Technology',
      industry: 'IT Services',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty IT'],
      fo: true,
      country: 'India',
      aliases: ['LTIMindtree', 'LTI Mindtree', 'LTIM', 'Mindtree']
    },
    {
      name: 'Coforge Limited',
      officialName: 'Coforge Limited',
      symbol: 'COFORGE',
      scripCode: '532541',
      isin: 'INE591G01017',
      exchange: 'NSE',
      sector: 'Technology',
      industry: 'IT Services',
      marketCap: 'Mid Cap',
      indices: ['Nifty IT', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Coforge', 'Coforge Ltd', 'NIIT Technologies']
    },
    {
      name: 'Persistent Systems Limited',
      officialName: 'Persistent Systems Limited',
      symbol: 'PERSISTENT',
      scripCode: '533179',
      isin: 'INE262H01021',
      exchange: 'NSE',
      sector: 'Technology',
      industry: 'IT Services',
      marketCap: 'Mid Cap',
      indices: ['Nifty IT', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Persistent Systems', 'Persistent', 'Persistent Systems Ltd']
    },
    {
      name: 'Polycab India Limited',
      officialName: 'Polycab India Limited',
      symbol: 'POLYCAB',
      scripCode: '542652',
      isin: 'INE455K01017',
      exchange: 'NSE',
      sector: 'Capital Goods',
      industry: 'Wires & Cables',
      marketCap: 'Large Cap',
      indices: ['Nifty Midcap 100', 'Nifty 500'],
      fo: true,
      country: 'India',
      aliases: ['Polycab', 'Polycab India', 'Polycab Ltd']
    },
    {
      name: 'Havells India Limited',
      officialName: 'Havells India Limited',
      symbol: 'HAVELLS',
      scripCode: '517354',
      isin: 'INE176B01034',
      exchange: 'NSE',
      sector: 'Consumer Durables',
      industry: 'Electrical Equipment',
      marketCap: 'Large Cap',
      indices: ['Nifty 100', 'Nifty Consumer Durables'],
      fo: true,
      country: 'India',
      aliases: ['Havells', 'Havells India', 'Havells India Ltd']
    },
    {
      name: 'Suzlon Energy Limited',
      officialName: 'Suzlon Energy Limited',
      symbol: 'SUZLON',
      scripCode: '532667',
      isin: 'INE040H01021',
      exchange: 'NSE',
      sector: 'Power',
      industry: 'Wind Energy Equipment',
      marketCap: 'Mid Cap',
      indices: ['Nifty Midcap 100', 'Nifty 500'],
      fo: true,
      country: 'India',
      aliases: ['Suzlon', 'Suzlon Energy', 'Suzlon Energy Ltd']
    },
    {
      name: 'One97 Communications Limited (Paytm)',
      officialName: 'One97 Communications Limited',
      symbol: 'PAYTM',
      scripCode: '543396',
      isin: 'INE982J01020',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Fintech',
      marketCap: 'Mid Cap',
      indices: ['Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Paytm', 'One97 Communications', 'One97']
    },
    {
      name: 'Eternal Ltd (Zomato)',
      officialName: 'Eternal Ltd',
      symbol: 'ETERNAL',
      scripCode: '543320',
      isin: 'INE758T01015',
      exchange: 'NSE',
      sector: 'Services',
      industry: 'Food Delivery & Quick Commerce',
      marketCap: 'Large Cap',
      indices: ['Nifty 100', 'Nifty 500'],
      fo: true,
      country: 'India',
      aliases: ['Zomato', 'Eternal', 'Blinkit', 'Zomato Ltd']
    },
    {
      name: 'Jio Financial Services Limited',
      officialName: 'Jio Financial Services Limited',
      symbol: 'JIOFIN',
      scripCode: '543940',
      isin: 'INE072Q01015',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'NBFC',
      marketCap: 'Large Cap',
      indices: ['Nifty 100', 'Nifty 500'],
      fo: true,
      country: 'India',
      aliases: ['Jio Financial', 'Jio Financial Services', 'JIOFIN', 'Jio Financial Services Ltd']
    },
    {
      name: 'Adani Enterprises Limited',
      officialName: 'Adani Enterprises Limited',
      symbol: 'ADANIENT',
      scripCode: '512599',
      isin: 'INE423A01024',
      exchange: 'NSE',
      sector: 'Metals & Mining',
      industry: 'Trading & Incubation',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['Adani Enterprises', 'Adani Ent', 'Adani Enterprises Ltd', 'Adani Group']
    },
    {
      name: 'Adani Ports and Special Economic Zone Limited',
      officialName: 'Adani Ports and Special Economic Zone Limited',
      symbol: 'ADANIPORTS',
      scripCode: '532921',
      isin: 'INE742H01013',
      exchange: 'NSE',
      sector: 'Services',
      industry: 'Ports & Marine Services',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['Adani Ports', 'APSEZ', 'Adani Ports and SEZ', 'Adani Ports Ltd']
    },
    {
      name: 'Tata Steel Limited',
      officialName: 'Tata Steel Limited',
      symbol: 'TATASTEEL',
      scripCode: '500470',
      isin: 'INE081A01020',
      exchange: 'NSE',
      sector: 'Metals & Mining',
      industry: 'Steel',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Metal'],
      fo: true,
      country: 'India',
      aliases: ['Tata Steel', 'TataSteel', 'Tata Steel Ltd']
    },
    {
      name: 'JSW Steel Limited',
      officialName: 'JSW Steel Limited',
      symbol: 'JSWSTEEL',
      scripCode: '500228',
      isin: 'INE019A01038',
      exchange: 'NSE',
      sector: 'Metals & Mining',
      industry: 'Steel',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Metal'],
      fo: true,
      country: 'India',
      aliases: ['JSW Steel', 'JSWSteel', 'JSW Steel Ltd']
    },
    {
      name: 'Hindalco Industries Limited',
      officialName: 'Hindalco Industries Limited',
      symbol: 'HINDALCO',
      scripCode: '500440',
      isin: 'INE038A01020',
      exchange: 'NSE',
      sector: 'Metals & Mining',
      industry: 'Aluminium',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Metal'],
      fo: true,
      country: 'India',
      aliases: ['Hindalco', 'Hindalco Industries', 'Hindalco Ltd', 'Novelis']
    },
    {
      name: 'Coal India Limited',
      officialName: 'Coal India Limited',
      symbol: 'COALINDIA',
      scripCode: '533278',
      isin: 'INE522F01014',
      exchange: 'NSE',
      sector: 'Energy',
      industry: 'Coal Mining',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Energy'],
      fo: true,
      country: 'India',
      aliases: ['Coal India', 'CoalIndia', 'CIL', 'Coal India Ltd']
    },
    {
      name: 'Oil and Natural Gas Corporation Limited',
      officialName: 'Oil and Natural Gas Corporation Limited',
      symbol: 'ONGC',
      scripCode: '500312',
      isin: 'INE213A01029',
      exchange: 'NSE',
      sector: 'Energy',
      industry: 'Oil Exploration',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Energy'],
      fo: true,
      country: 'India',
      aliases: ['ONGC', 'Oil and Natural Gas Corporation', 'Oil & Natural Gas Corp']
    },
    {
      name: 'NTPC Limited',
      officialName: 'NTPC Limited',
      symbol: 'NTPC',
      scripCode: '532555',
      isin: 'INE733E01010',
      exchange: 'NSE',
      sector: 'Power',
      industry: 'Power Generation',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Infrastructure'],
      fo: true,
      country: 'India',
      aliases: ['NTPC', 'NTPC Ltd', 'NTPC Limited']
    },
    {
      name: 'Power Grid Corporation of India Limited',
      officialName: 'Power Grid Corporation of India Limited',
      symbol: 'POWERGRID',
      scripCode: '532898',
      isin: 'INE752E01010',
      exchange: 'NSE',
      sector: 'Power',
      industry: 'Power Transmission',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Infrastructure'],
      fo: true,
      country: 'India',
      aliases: ['Power Grid', 'Powergrid', 'PGCIL', 'Power Grid Corp']
    },
    {
      name: 'UltraTech Cement Limited',
      officialName: 'UltraTech Cement Limited',
      symbol: 'ULTRACEMCO',
      scripCode: '532538',
      isin: 'INE481G01011',
      exchange: 'NSE',
      sector: 'Basic Materials',
      industry: 'Cement',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Infrastructure'],
      fo: true,
      country: 'India',
      aliases: ['UltraTech Cement', 'UltraTech', 'Ultracemco', 'UltraTech Cement Ltd']
    },
    {
      name: 'Bajaj Finance Limited',
      officialName: 'Bajaj Finance Limited',
      symbol: 'BAJFINANCE',
      scripCode: '500034',
      isin: 'INE296A01024',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'NBFC',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Financial Services'],
      fo: true,
      country: 'India',
      aliases: ['Bajaj Finance', 'Bajfinance', 'Bajaj Finance Ltd']
    },
    {
      name: 'Bajaj Finserv Limited',
      officialName: 'Bajaj Finserv Limited',
      symbol: 'BAJAJFINSV',
      scripCode: '532978',
      isin: 'INE918I01024',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Holding Company',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Financial Services'],
      fo: true,
      country: 'India',
      aliases: ['Bajaj Finserv', 'Bajajfinsv', 'Bajaj Finserv Ltd']
    },
    {
      name: 'Cipla Limited',
      officialName: 'Cipla Limited',
      symbol: 'CIPLA',
      scripCode: '500087',
      isin: 'INE059A01026',
      exchange: 'NSE',
      sector: 'Healthcare',
      industry: 'Pharmaceuticals',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Pharma'],
      fo: true,
      country: 'India',
      aliases: ['Cipla', 'Cipla Ltd', 'Cipla Limited']
    },
    {
      name: 'Dr. Reddy\'s Laboratories Limited',
      officialName: 'Dr. Reddy\'s Laboratories Limited',
      symbol: 'DRREDDY',
      scripCode: '500124',
      isin: 'INE089A01023',
      exchange: 'NSE',
      sector: 'Healthcare',
      industry: 'Pharmaceuticals',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Pharma'],
      fo: true,
      country: 'India',
      aliases: ['Dr. Reddy\'s', 'Dr Reddys', 'Dr Reddy', 'Dr. Reddy Laboratories', 'DRREDDY']
    },
    {
      name: 'Divi\'s Laboratories Limited',
      officialName: 'Divi\'s Laboratories Limited',
      symbol: 'DIVISLAB',
      scripCode: '532488',
      isin: 'INE361B01024',
      exchange: 'NSE',
      sector: 'Healthcare',
      industry: 'API / Pharmaceuticals',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Pharma'],
      fo: true,
      country: 'India',
      aliases: ['Divi\'s Lab', 'Divis Lab', 'Divi\'s Laboratories', 'DIVISLAB']
    },
    {
      name: 'Eicher Motors Limited',
      officialName: 'Eicher Motors Limited',
      symbol: 'EICHERMOT',
      scripCode: '505200',
      isin: 'INE066A01021',
      exchange: 'NSE',
      sector: 'Automobile',
      industry: 'Premium Motorcycles',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Auto'],
      fo: true,
      country: 'India',
      aliases: ['Eicher Motors', 'Royal Enfield', 'Eicher', 'Eicher Motors Ltd']
    },
    {
      name: 'Hero MotoCorp Limited',
      officialName: 'Hero MotoCorp Limited',
      symbol: 'HEROMOTOCO',
      scripCode: '500182',
      isin: 'INE158A01026',
      exchange: 'NSE',
      sector: 'Automobile',
      industry: 'Two Wheelers',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Auto'],
      fo: true,
      country: 'India',
      aliases: ['Hero MotoCorp', 'Hero Moto', 'Hero', 'Hero Honda']
    },
    {
      name: 'Bajaj Auto Limited',
      officialName: 'Bajaj Auto Limited',
      symbol: 'BAJAJ-AUTO',
      scripCode: '532977',
      isin: 'INE917I01010',
      exchange: 'NSE',
      sector: 'Automobile',
      industry: 'Two & Three Wheelers',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Auto'],
      fo: true,
      country: 'India',
      aliases: ['Bajaj Auto', 'Bajaj Auto Ltd', 'BAJAJ-AUTO']
    },
    {
      name: 'TVS Motor Company Limited',
      officialName: 'TVS Motor Company Limited',
      symbol: 'TVSMOTOR',
      scripCode: '532343',
      isin: 'INE494B01023',
      exchange: 'NSE',
      sector: 'Automobile',
      industry: 'Two Wheelers',
      marketCap: 'Large Cap',
      indices: ['Nifty Auto', 'Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['TVS Motor', 'TVS Motor Company', 'TVS', 'TVSMotor']
    },
    {
      name: 'Bharat Petroleum Corporation Limited',
      officialName: 'Bharat Petroleum Corporation Limited',
      symbol: 'BPCL',
      scripCode: '500547',
      isin: 'INE029A01011',
      exchange: 'NSE',
      sector: 'Energy',
      industry: 'Oil Refining & Marketing',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Energy'],
      fo: true,
      country: 'India',
      aliases: ['BPCL', 'Bharat Petroleum', 'Bharat Petroleum Corporation']
    },
    {
      name: 'Hindustan Petroleum Corporation Limited',
      officialName: 'Hindustan Petroleum Corporation Limited',
      symbol: 'HPCL',
      scripCode: '500104',
      isin: 'INE094A01015',
      exchange: 'NSE',
      sector: 'Energy',
      industry: 'Oil Refining & Marketing',
      marketCap: 'Mid Cap',
      indices: ['Nifty Energy', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['HPCL', 'Hindustan Petroleum', 'Hindustan Petroleum Corporation']
    },
    {
      name: 'Indian Oil Corporation Limited',
      officialName: 'Indian Oil Corporation Limited',
      symbol: 'IOC',
      scripCode: '530965',
      isin: 'INE242A01010',
      exchange: 'NSE',
      sector: 'Energy',
      industry: 'Oil Refining & Marketing',
      marketCap: 'Large Cap',
      indices: ['Nifty 100', 'Nifty Energy'],
      fo: true,
      country: 'India',
      aliases: ['IOC', 'IOCL', 'Indian Oil', 'Indian Oil Corporation']
    },
    {
      name: 'GAIL (India) Limited',
      officialName: 'GAIL (India) Limited',
      symbol: 'GAIL',
      scripCode: '532155',
      isin: 'INE129A01019',
      exchange: 'NSE',
      sector: 'Energy',
      industry: 'Gas Utilities',
      marketCap: 'Large Cap',
      indices: ['Nifty 100', 'Nifty Energy'],
      fo: true,
      country: 'India',
      aliases: ['GAIL', 'GAIL India', 'Gail']
    },
    {
      name: 'Tata Power Company Limited',
      officialName: 'Tata Power Company Limited',
      symbol: 'TATAPOWER',
      scripCode: '500400',
      isin: 'INE245A01021',
      exchange: 'NSE',
      sector: 'Power',
      industry: 'Integrated Power',
      marketCap: 'Large Cap',
      indices: ['Nifty 100', 'Nifty Infrastructure'],
      fo: true,
      country: 'India',
      aliases: ['Tata Power', 'Tatapower', 'Tata Power Ltd']
    },
    {
      name: 'Adani Power Limited',
      officialName: 'Adani Power Limited',
      symbol: 'ADANIPOWER',
      scripCode: '533096',
      isin: 'INE814H01011',
      exchange: 'NSE',
      sector: 'Power',
      industry: 'Power Generation',
      marketCap: 'Large Cap',
      indices: ['Nifty 100', 'Nifty Infrastructure'],
      fo: true,
      country: 'India',
      aliases: ['Adani Power', 'Adanipower', 'Adani Power Ltd']
    },
    {
      name: 'Adani Green Energy Limited',
      officialName: 'Adani Green Energy Limited',
      symbol: 'ADANIGREEN',
      scripCode: '541450',
      isin: 'INE364U01010',
      exchange: 'NSE',
      sector: 'Power',
      industry: 'Renewable Power',
      marketCap: 'Large Cap',
      indices: ['Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['Adani Green', 'Adanigreen', 'Adani Green Energy']
    },
    {
      name: 'JSW Energy Limited',
      officialName: 'JSW Energy Limited',
      symbol: 'JSWENERGY',
      scripCode: '533148',
      isin: 'INE121E01018',
      exchange: 'NSE',
      sector: 'Power',
      industry: 'Power Generation',
      marketCap: 'Large Cap',
      indices: ['Nifty 100', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['JSW Energy', 'Jswenergy', 'JSW Energy Ltd']
    },
    {
      name: 'Ashok Leyland Limited',
      officialName: 'Ashok Leyland Limited',
      symbol: 'ASHOKLEY',
      scripCode: '500477',
      isin: 'INE208A01029',
      exchange: 'NSE',
      sector: 'Automobile',
      industry: 'Commercial Vehicles',
      marketCap: 'Large Cap',
      indices: ['Nifty Auto', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Ashok Leyland', 'Ashokley', 'Ashok Leyland Ltd']
    },
    {
      name: 'Bharat Forge Limited',
      officialName: 'Bharat Forge Limited',
      symbol: 'BHARATFORG',
      scripCode: '500493',
      isin: 'INE465A01025',
      exchange: 'NSE',
      sector: 'Capital Goods',
      industry: 'Auto Ancillaries / Forging',
      marketCap: 'Large Cap',
      indices: ['Nifty Auto', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Bharat Forge', 'Bharatforg', 'Bharat Forge Ltd']
    },
    {
      name: 'Samvardhana Motherson International Limited',
      officialName: 'Samvardhana Motherson International Limited',
      symbol: 'MOTHERSON',
      scripCode: '517334',
      isin: 'INE775A01035',
      exchange: 'NSE',
      sector: 'Automobile',
      industry: 'Auto Ancillaries',
      marketCap: 'Large Cap',
      indices: ['Nifty Auto', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Motherson', 'Motherson Sumi', 'Samvardhana Motherson']
    },
    {
      name: 'DLF Limited',
      officialName: 'DLF Limited',
      symbol: 'DLF',
      scripCode: '532868',
      isin: 'INE271C01023',
      exchange: 'NSE',
      sector: 'Real Estate',
      industry: 'Real Estate Development',
      marketCap: 'Large Cap',
      indices: ['Nifty Realty', 'Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['DLF', 'DLF Ltd', 'DLF Limited']
    },
    {
      name: 'Godrej Properties Limited',
      officialName: 'Godrej Properties Limited',
      symbol: 'GODREJPROP',
      scripCode: '533150',
      isin: 'INE484J01027',
      exchange: 'NSE',
      sector: 'Real Estate',
      industry: 'Real Estate Development',
      marketCap: 'Large Cap',
      indices: ['Nifty Realty', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Godrej Properties', 'Godrejprop', 'Godrej Properties Ltd']
    },
    {
      name: 'Oberoi Realty Limited',
      officialName: 'Oberoi Realty Limited',
      symbol: 'OBEROIRLTY',
      scripCode: '533273',
      isin: 'INE093I01010',
      exchange: 'NSE',
      sector: 'Real Estate',
      industry: 'Real Estate Development',
      marketCap: 'Large Cap',
      indices: ['Nifty Realty', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Oberoi Realty', 'Oberoirlty', 'Oberoi Realty Ltd']
    },
    {
      name: 'Asian Paints Limited',
      officialName: 'Asian Paints Limited',
      symbol: 'ASIANPAINT',
      scripCode: '500820',
      isin: 'INE021A01026',
      exchange: 'NSE',
      sector: 'Consumer Discretionary',
      industry: 'Paints',
      marketCap: 'Large Cap',
      indices: ['Nifty 50'],
      fo: true,
      country: 'India',
      aliases: ['Asian Paints', 'Asianpaint', 'Asian Paints Ltd']
    },
    {
      name: 'Pidilite Industries Limited',
      officialName: 'Pidilite Industries Limited',
      symbol: 'PIDILITIND',
      scripCode: '500331',
      isin: 'INE318A01026',
      exchange: 'NSE',
      sector: 'Basic Materials',
      industry: 'Adhesives & Chemicals',
      marketCap: 'Large Cap',
      indices: ['Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['Pidilite', 'Pidilitind', 'Fevicol', 'Pidilite Industries']
    },
    {
      name: 'Trent Limited',
      officialName: 'Trent Limited',
      symbol: 'TRENT',
      scripCode: '500251',
      isin: 'INE849A01020',
      exchange: 'NSE',
      sector: 'Consumer Discretionary',
      industry: 'Apparel Retail',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['Trent', 'Zudio', 'Westside', 'Trent Ltd']
    },
    {
      name: 'Voltas Limited',
      officialName: 'Voltas Limited',
      symbol: 'VOLTAS',
      scripCode: '500575',
      isin: 'INE226A01021',
      exchange: 'NSE',
      sector: 'Consumer Durables',
      industry: 'Air Conditioning',
      marketCap: 'Large Cap',
      indices: ['Nifty Midcap 100', 'Nifty Consumer Durables'],
      fo: true,
      country: 'India',
      aliases: ['Voltas', 'Voltas Ltd']
    },
    {
      name: 'Siemens Limited',
      officialName: 'Siemens Limited',
      symbol: 'SIEMENS',
      scripCode: '500550',
      isin: 'INE003A01024',
      exchange: 'NSE',
      sector: 'Capital Goods',
      industry: 'Electrical Equipment',
      marketCap: 'Large Cap',
      indices: ['Nifty 100', 'Nifty Infrastructure'],
      fo: true,
      country: 'India',
      aliases: ['Siemens', 'Siemens India', 'Siemens Ltd']
    },
    {
      name: 'ABB India Limited',
      officialName: 'ABB India Limited',
      symbol: 'ABB',
      scripCode: '500002',
      isin: 'INE117A01022',
      exchange: 'NSE',
      sector: 'Capital Goods',
      industry: 'Electrical Equipment',
      marketCap: 'Large Cap',
      indices: ['Nifty 100', 'Nifty Infrastructure'],
      fo: true,
      country: 'India',
      aliases: ['ABB', 'ABB India', 'ABB Ltd']
    },
    {
      name: 'Cummins India Limited',
      officialName: 'Cummins India Limited',
      symbol: 'CUMMINSIND',
      scripCode: '500480',
      isin: 'INE298A01020',
      exchange: 'NSE',
      sector: 'Capital Goods',
      industry: 'Engines & Generators',
      marketCap: 'Large Cap',
      indices: ['Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Cummins', 'Cummins India', 'Cumminsind']
    },
    {
      name: 'Bharat Heavy Electricals Limited',
      officialName: 'Bharat Heavy Electricals Limited',
      symbol: 'BHEL',
      scripCode: '500103',
      isin: 'INE257A01026',
      exchange: 'NSE',
      sector: 'Capital Goods',
      industry: 'Heavy Electricals',
      marketCap: 'Large Cap',
      indices: ['Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['BHEL', 'Bharat Heavy Electricals', 'Bharat Heavy Electricals Ltd']
    },
    {
      name: 'Container Corporation of India Limited',
      officialName: 'Container Corporation of India Limited',
      symbol: 'CONCOR',
      scripCode: '531344',
      isin: 'INE111A01025',
      exchange: 'NSE',
      sector: 'Services',
      industry: 'Logistics',
      marketCap: 'Large Cap',
      indices: ['Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['CONCOR', 'Container Corporation', 'Container Corp']
    },
    {
      name: 'Ambuja Cements Limited',
      officialName: 'Ambuja Cements Limited',
      symbol: 'AMBUJACEM',
      scripCode: '500425',
      isin: 'INE079A01024',
      exchange: 'NSE',
      sector: 'Basic Materials',
      industry: 'Cement',
      marketCap: 'Large Cap',
      indices: ['Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['Ambuja Cement', 'Ambuja Cements', 'Ambujacem']
    },
    {
      name: 'ACC Limited',
      officialName: 'ACC Limited',
      symbol: 'ACC',
      scripCode: '500410',
      isin: 'INE012A01025',
      exchange: 'NSE',
      sector: 'Basic Materials',
      industry: 'Cement',
      marketCap: 'Large Cap',
      indices: ['Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['ACC', 'ACC Cement', 'ACC Ltd']
    },
    {
      name: 'Grasim Industries Limited',
      officialName: 'Grasim Industries Limited',
      symbol: 'GRASIM',
      scripCode: '500300',
      isin: 'INE047A01021',
      exchange: 'NSE',
      sector: 'Basic Materials',
      industry: 'Diversified Materials',
      marketCap: 'Large Cap',
      indices: ['Nifty 50'],
      fo: true,
      country: 'India',
      aliases: ['Grasim', 'Grasim Industries', 'Grasim Ltd']
    },
    {
      name: 'InterGlobe Aviation Limited (IndiGo)',
      officialName: 'InterGlobe Aviation Limited',
      symbol: 'INDIGO',
      scripCode: '539448',
      isin: 'INE646L01027',
      exchange: 'NSE',
      sector: 'Services',
      industry: 'Airlines',
      marketCap: 'Large Cap',
      indices: ['Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['IndiGo', 'Indigo Airline', 'InterGlobe Aviation', 'IndiGo Airlines']
    },
    {
      name: 'Indus Towers Limited',
      officialName: 'Indus Towers Limited',
      symbol: 'INDUSTOWER',
      scripCode: '534816',
      isin: 'INE121J01017',
      exchange: 'NSE',
      sector: 'Telecommunication',
      industry: 'Telecom Infrastructure',
      marketCap: 'Large Cap',
      indices: ['Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Indus Towers', 'Industower', 'Bharti Infratel']
    },
    {
      name: 'Multi Commodity Exchange of India Limited',
      officialName: 'Multi Commodity Exchange of India Limited',
      symbol: 'MCX',
      scripCode: '534091',
      isin: 'INE745G01035',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Financial Exchange',
      marketCap: 'Mid Cap',
      indices: ['Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['MCX', 'Multi Commodity Exchange', 'MCX India']
    },
    {
      name: 'BSE Limited',
      officialName: 'BSE Limited',
      symbol: 'BSE',
      scripCode: '540115',
      isin: 'INE118H01025',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Financial Exchange',
      marketCap: 'Mid Cap',
      indices: ['Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['BSE Ltd', 'BSE Limited', 'Bombay Stock Exchange']
    },
    {
      name: 'Central Depository Services (India) Limited',
      officialName: 'Central Depository Services (India) Limited',
      symbol: 'CDSL',
      scripCode: '540615',
      isin: 'INE736A01011',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Depository',
      marketCap: 'Mid Cap',
      indices: ['Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['CDSL', 'Central Depository Services', 'CDSL India']
    },
    {
      name: 'Dabur India Limited',
      officialName: 'Dabur India Limited',
      symbol: 'DABUR',
      scripCode: '500096',
      isin: 'INE016A01026',
      exchange: 'NSE',
      sector: 'Consumer Goods',
      industry: 'FMCG',
      marketCap: 'Large Cap',
      indices: ['Nifty FMCG', 'Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['Dabur', 'Dabur India', 'Dabur Ltd']
    },
    {
      name: 'Marico Limited',
      officialName: 'Marico Limited',
      symbol: 'MARICO',
      scripCode: '531642',
      isin: 'INE196A01026',
      exchange: 'NSE',
      sector: 'Consumer Goods',
      industry: 'FMCG',
      marketCap: 'Large Cap',
      indices: ['Nifty FMCG', 'Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['Marico', 'Saffola', 'Parachute', 'Marico Ltd']
    },
    {
      name: 'Hindustan Unilever Limited',
      officialName: 'Hindustan Unilever Limited',
      symbol: 'HINDUNILVR',
      scripCode: '500696',
      isin: 'INE030A01027',
      exchange: 'NSE',
      sector: 'Consumer Goods',
      industry: 'FMCG',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty FMCG'],
      fo: true,
      country: 'India',
      aliases: ['HUL', 'Hindustan Unilever', 'Hindunilvr', 'Hindustan Unilever Ltd']
    },
    {
      name: 'Varun Beverages Limited',
      officialName: 'Varun Beverages Limited',
      symbol: 'VBL',
      scripCode: '540180',
      isin: 'INE200M01021',
      exchange: 'NSE',
      sector: 'Consumer Goods',
      industry: 'Beverages',
      marketCap: 'Large Cap',
      indices: ['Nifty 100', 'Nifty FMCG'],
      fo: true,
      country: 'India',
      aliases: ['Varun Beverages', 'VBL', 'Pepsi India']
    },
    {
      name: 'Britannia Industries Limited',
      officialName: 'Britannia Industries Limited',
      symbol: 'BRITANNIA',
      scripCode: '500825',
      isin: 'INE216A01030',
      exchange: 'NSE',
      sector: 'Consumer Goods',
      industry: 'Packaged Foods',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty FMCG'],
      fo: true,
      country: 'India',
      aliases: ['Britannia', 'Britannia Industries', 'Britannia Ltd']
    },
    {
      name: 'Tata Consumer Products Limited',
      officialName: 'Tata Consumer Products Limited',
      symbol: 'TATACONSUM',
      scripCode: '500800',
      isin: 'INE192A01025',
      exchange: 'NSE',
      sector: 'Consumer Goods',
      industry: 'FMCG & Beverages',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty FMCG'],
      fo: true,
      country: 'India',
      aliases: ['Tata Consumer', 'Tataconsum', 'Tata Tea', 'Tata Salt']
    },
    {
      name: 'Lupin Limited',
      officialName: 'Lupin Limited',
      symbol: 'LUPIN',
      scripCode: '500257',
      isin: 'INE326A01037',
      exchange: 'NSE',
      sector: 'Healthcare',
      industry: 'Pharmaceuticals',
      marketCap: 'Large Cap',
      indices: ['Nifty Pharma', 'Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['Lupin', 'Lupin Ltd', 'Lupin Pharma']
    },
    {
      name: 'Aurobindo Pharma Limited',
      officialName: 'Aurobindo Pharma Limited',
      symbol: 'AUROPHARMA',
      scripCode: '524804',
      isin: 'INE406A01037',
      exchange: 'NSE',
      sector: 'Healthcare',
      industry: 'Pharmaceuticals',
      marketCap: 'Large Cap',
      indices: ['Nifty Pharma', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Aurobindo Pharma', 'Auropharma', 'Aurobindo']
    },
    {
      name: 'Biocon Limited',
      officialName: 'Biocon Limited',
      symbol: 'BIOCON',
      scripCode: '532523',
      isin: 'INE376G01013',
      exchange: 'NSE',
      sector: 'Healthcare',
      industry: 'Biotechnology',
      marketCap: 'Mid Cap',
      indices: ['Nifty Pharma', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Biocon', 'Biocon Ltd']
    },
    {
      name: 'Zydus Lifesciences Limited',
      officialName: 'Zydus Lifesciences Limited',
      symbol: 'ZYDUSLIFE',
      scripCode: '532321',
      isin: 'INE010B01027',
      exchange: 'NSE',
      sector: 'Healthcare',
      industry: 'Pharmaceuticals',
      marketCap: 'Large Cap',
      indices: ['Nifty Pharma', 'Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['Zydus Life', 'Zyduslife', 'Cadila Healthcare', 'Zydus']
    },
    {
      name: 'Apollo Hospitals Enterprise Limited',
      officialName: 'Apollo Hospitals Enterprise Limited',
      symbol: 'APOLLOHOSP',
      scripCode: '508869',
      isin: 'INE437A01024',
      exchange: 'NSE',
      sector: 'Healthcare',
      industry: 'Hospitals',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Healthcare'],
      fo: true,
      country: 'India',
      aliases: ['Apollo Hospitals', 'Apollohosp', 'Apollo Hospital', 'Apollo Hospitals Ltd']
    },
    {
      name: 'Max Healthcare Institute Limited',
      officialName: 'Max Healthcare Institute Limited',
      symbol: 'MAXHEALTH',
      scripCode: '543220',
      isin: 'INE026L01022',
      exchange: 'NSE',
      sector: 'Healthcare',
      industry: 'Hospitals',
      marketCap: 'Large Cap',
      indices: ['Nifty Healthcare', 'Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['Max Healthcare', 'Maxhealth', 'Max Hospital']
    },
    {
      name: 'Vedanta Limited',
      officialName: 'Vedanta Limited',
      symbol: 'VEDL',
      scripCode: '500295',
      isin: 'INE205A01025',
      exchange: 'NSE',
      sector: 'Metals & Mining',
      industry: 'Diversified Metals',
      marketCap: 'Large Cap',
      indices: ['Nifty Metal', 'Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['Vedanta', 'Vedl', 'Vedanta Ltd']
    },
    {
      name: 'Jindal Steel & Power Limited',
      officialName: 'Jindal Steel & Power Limited',
      symbol: 'JINDALSTEL',
      scripCode: '532286',
      isin: 'INE749A01030',
      exchange: 'NSE',
      sector: 'Metals & Mining',
      industry: 'Steel',
      marketCap: 'Large Cap',
      indices: ['Nifty Metal', 'Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['Jindal Steel', 'Jindalstel', 'JSPL', 'Jindal Steel and Power']
    },
    {
      name: 'NMDC Limited',
      officialName: 'NMDC Limited',
      symbol: 'NMDC',
      scripCode: '526371',
      isin: 'INE584A01023',
      exchange: 'NSE',
      sector: 'Metals & Mining',
      industry: 'Iron Ore Mining',
      marketCap: 'Large Cap',
      indices: ['Nifty Metal', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['NMDC', 'NMDC Ltd', 'National Mineral Development Corporation']
    },
    {
      name: 'Steel Authority of India Limited',
      officialName: 'Steel Authority of India Limited',
      symbol: 'SAIL',
      scripCode: '500113',
      isin: 'INE114A01011',
      exchange: 'NSE',
      sector: 'Metals & Mining',
      industry: 'Steel',
      marketCap: 'Large Cap',
      indices: ['Nifty Metal', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['SAIL', 'Steel Authority of India', 'Steel Authority']
    },
    {
      name: 'National Aluminium Company Limited',
      officialName: 'National Aluminium Company Limited',
      symbol: 'NATIONALUM',
      scripCode: '532234',
      isin: 'INE139A01034',
      exchange: 'NSE',
      sector: 'Metals & Mining',
      industry: 'Aluminium',
      marketCap: 'Mid Cap',
      indices: ['Nifty Metal', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['NALCO', 'Nationalum', 'National Aluminium']
    },
    {
      name: 'Hindustan Copper Limited',
      officialName: 'Hindustan Copper Limited',
      symbol: 'HINDCOPPER',
      scripCode: '513599',
      isin: 'INE531E01026',
      exchange: 'NSE',
      sector: 'Metals & Mining',
      industry: 'Copper Mining',
      marketCap: 'Mid Cap',
      indices: ['Nifty Metal', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Hindustan Copper', 'Hindcopper', 'Hindustan Copper Ltd']
    },
    {
      name: 'Shriram Finance Limited',
      officialName: 'Shriram Finance Limited',
      symbol: 'SHRIRAMFIN',
      scripCode: '511218',
      isin: 'INE721A01013',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'NBFC',
      marketCap: 'Large Cap',
      indices: ['Nifty 50', 'Nifty Financial Services'],
      fo: true,
      country: 'India',
      aliases: ['Shriram Finance', 'Shriramfin', 'Shriram Transport Finance']
    },
    {
      name: 'Cholamandalam Investment and Finance Company',
      officialName: 'Cholamandalam Investment and Finance Company Limited',
      symbol: 'CHOLAFIN',
      scripCode: '511243',
      isin: 'INE121A01024',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'NBFC',
      marketCap: 'Large Cap',
      indices: ['Nifty 100', 'Nifty Financial Services'],
      fo: true,
      country: 'India',
      aliases: ['Cholamandalam', 'Cholafin', 'Chola', 'Cholamandalam Investment']
    },
    {
      name: 'Muthoot Finance Limited',
      officialName: 'Muthoot Finance Limited',
      symbol: 'MUTHOOTFIN',
      scripCode: '533398',
      isin: 'INE414G01012',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Gold Finance',
      marketCap: 'Large Cap',
      indices: ['Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Muthoot Finance', 'Muthootfin', 'Muthoot']
    },
    {
      name: 'Power Finance Corporation Limited',
      officialName: 'Power Finance Corporation Limited',
      symbol: 'PFC',
      scripCode: '532810',
      isin: 'INE134E01011',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Power NBFC',
      marketCap: 'Large Cap',
      indices: ['Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['PFC', 'Power Finance Corporation', 'Power Finance Corp']
    },
    {
      name: 'REC Limited',
      officialName: 'REC Limited',
      symbol: 'RECLTD',
      scripCode: '532955',
      isin: 'INE020B01018',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Power NBFC',
      marketCap: 'Large Cap',
      indices: ['Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['REC Limited', 'Recltd', 'REC', 'Rural Electrification Corp']
    },
    {
      name: 'SBI Life Insurance Company Limited',
      officialName: 'SBI Life Insurance Company Limited',
      symbol: 'SBILIFE',
      scripCode: '540719',
      isin: 'INE123W01016',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Life Insurance',
      marketCap: 'Large Cap',
      indices: ['Nifty 50'],
      fo: true,
      country: 'India',
      aliases: ['SBI Life', 'Sbilife', 'SBI Life Insurance']
    },
    {
      name: 'HDFC Life Insurance Company Limited',
      officialName: 'HDFC Life Insurance Company Limited',
      symbol: 'HDFCLIFE',
      scripCode: '540777',
      isin: 'INE795G01014',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Life Insurance',
      marketCap: 'Large Cap',
      indices: ['Nifty 50'],
      fo: true,
      country: 'India',
      aliases: ['HDFC Life', 'Hdfclife', 'HDFC Life Insurance']
    },
    {
      name: 'Life Insurance Corporation of India',
      officialName: 'Life Insurance Corporation of India',
      symbol: 'LICI',
      scripCode: '543526',
      isin: 'INE115A01015',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Life Insurance',
      marketCap: 'Large Cap',
      indices: ['Nifty 100'],
      fo: true,
      country: 'India',
      aliases: ['LIC', 'LIC India', 'LICI', 'Life Insurance Corporation']
    },
    {
      name: 'Punjab National Bank',
      officialName: 'Punjab National Bank',
      symbol: 'PNB',
      scripCode: '532461',
      isin: 'INE160A01022',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Public Bank',
      marketCap: 'Large Cap',
      indices: ['Nifty PSU Bank', 'Nifty Bank'],
      fo: true,
      country: 'India',
      aliases: ['PNB', 'Punjab National Bank']
    },
    {
      name: 'Bank of Baroda',
      officialName: 'Bank of Baroda',
      symbol: 'BANKBARODA',
      scripCode: '532134',
      isin: 'INE028A01039',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Public Bank',
      marketCap: 'Large Cap',
      indices: ['Nifty PSU Bank', 'Nifty Bank'],
      fo: true,
      country: 'India',
      aliases: ['Bank of Baroda', 'Bankbaroda', 'BOB']
    },
    {
      name: 'Canara Bank',
      officialName: 'Canara Bank',
      symbol: 'CANBK',
      scripCode: '532483',
      isin: 'INE476A01022',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Public Bank',
      marketCap: 'Large Cap',
      indices: ['Nifty PSU Bank', 'Nifty Bank'],
      fo: true,
      country: 'India',
      aliases: ['Canara Bank', 'Canbk']
    },
    {
      name: 'IDFC First Bank Limited',
      officialName: 'IDFC First Bank Limited',
      symbol: 'IDFCFIRSTB',
      scripCode: '539437',
      isin: 'INE092T01019',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Private Bank',
      marketCap: 'Large Cap',
      indices: ['Nifty Bank', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['IDFC First Bank', 'Idfcfirstb', 'IDFC First']
    },
    {
      name: 'Federal Bank Limited',
      officialName: 'Federal Bank Limited',
      symbol: 'FEDERALBNK',
      scripCode: '500469',
      isin: 'INE171A01029',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Private Bank',
      marketCap: 'Large Cap',
      indices: ['Nifty Bank', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Federal Bank', 'Federalbnk']
    },
    {
      name: 'AU Small Finance Bank Limited',
      officialName: 'AU Small Finance Bank Limited',
      symbol: 'AUBANK',
      scripCode: '540611',
      isin: 'INE949L01017',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Small Finance Bank',
      marketCap: 'Large Cap',
      indices: ['Nifty Bank', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['AU Bank', 'Aubank', 'AU Small Finance Bank']
    },
    {
      name: 'Bandhan Bank Limited',
      officialName: 'Bandhan Bank Limited',
      symbol: 'BANDHANBNK',
      scripCode: '541153',
      isin: 'INE545U01014',
      exchange: 'NSE',
      sector: 'Financial Services',
      industry: 'Private Bank',
      marketCap: 'Mid Cap',
      indices: ['Nifty Bank', 'Nifty Midcap 100'],
      fo: true,
      country: 'India',
      aliases: ['Bandhan Bank', 'Bandhanbnk']
    },
    {
      name: 'Zen Technologies Limited',
      officialName: 'Zen Technologies Limited',
      symbol: 'ZENTEC',
      scripCode: '533333',
      isin: 'INE251B01027',
      exchange: 'NSE',
      sector: 'Defence',
      industry: 'Defence Electronics & Simulators',
      marketCap: 'Small Cap',
      indices: ['Nifty Defence', 'Nifty Smallcap 250'],
      fo: false,
      country: 'India',
      aliases: ['Zen Tech', 'Zen Technologies', 'Zen Tech Ltd']
    }
  ];

  public static getAllRecords(): CompanyMasterRecord[] {
    return this.MASTER_RECORDS;
  }

  public static findBySymbol(symbol?: string): CompanyMasterRecord | null {
    if (!symbol) return null;
    const cleanSym = symbol.trim().toUpperCase();
    return this.MASTER_RECORDS.find(r => r.symbol.toUpperCase() === cleanSym) || null;
  }

  public static findByScripCode(scripCode?: string): CompanyMasterRecord | null {
    if (!scripCode) return null;
    const cleanScrip = scripCode.trim();
    return this.MASTER_RECORDS.find(r => r.scripCode === cleanScrip) || null;
  }

  public static findByIsin(isin?: string): CompanyMasterRecord | null {
    if (!isin) return null;
    const cleanIsin = isin.trim().toUpperCase();
    return this.MASTER_RECORDS.find(r => r.isin && r.isin.toUpperCase() === cleanIsin) || null;
  }

  public static findByCin(cin?: string): CompanyMasterRecord | null {
    if (!cin) return null;
    const cleanCin = cin.trim().toUpperCase();
    return this.MASTER_RECORDS.find(r => r.cin && (r.cin.toUpperCase() === cleanCin || cleanCin.includes(r.cin.toUpperCase()))) || null;
  }

  public static findByDomain(domain?: string): CompanyMasterRecord | null {
    if (!domain) return null;
    const cleanDom = domain.trim().toLowerCase().replace(/^https?:\/\//, '').replace(/^www\./, '');
    return this.MASTER_RECORDS.find(r => (r.website && r.website.toLowerCase().includes(cleanDom)) || (r.emailDomain && r.emailDomain.toLowerCase() === cleanDom)) || null;
  }

  public static findByNameOrAlias(query?: string): CompanyMasterRecord | null {
    if (!query) return null;
    const cleanQ = query.trim().toLowerCase();

    const matches: { record: CompanyMasterRecord; length: number }[] = [];

    for (const r of this.MASTER_RECORDS) {
      const candidates = [r.name, r.officialName, r.symbol, ...r.aliases].filter(Boolean) as string[];
      for (const cand of candidates) {
        if (!cand || cand.length < 2) continue;
        const escaped = cand.toLowerCase().replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&');
        const regex = new RegExp(`\\b${escaped}\\b`, 'i');
        if (regex.test(cleanQ)) {
          matches.push({ record: r, length: cand.length });
        }
      }
    }

    if (matches.length === 0) return null;
    matches.sort((a, b) => b.length - a.length);
    return matches[0].record;
  }

  public static getPeersForCompany(query?: string): CompanyMasterRecord[] {
    if (!query) return [];
    const clean = query.trim();
    const record = this.findBySymbol(clean) || this.findByNameOrAlias(clean);

    if (record) {
      const sym = record.symbol.toUpperCase();
      if (sym === 'BEL' || record.name.includes('Bharat Electronics') || record.sector === 'Defence' || record.industry.includes('Defence')) {
        const peerSymbols = ['HAL', 'BDL', 'DATAPATTNS', 'MAZDOCK', 'COCHINSHIP'];
        const list = peerSymbols
          .map(s => this.findBySymbol(s) || this.findByNameOrAlias(s))
          .filter((p): p is CompanyMasterRecord => p !== null && p.symbol !== sym);
        if (list.length > 0) return list;
      }

      return this.MASTER_RECORDS.filter(r => 
        r.symbol !== record.symbol && 
        (r.sector === record.sector || r.industry === record.industry)
      ).slice(0, 6);
    }

    return this.MASTER_RECORDS.filter(r => 
      r.sector.toLowerCase().includes(clean.toLowerCase()) || 
      r.industry.toLowerCase().includes(clean.toLowerCase())
    ).slice(0, 6);
  }
}
