/**
 * ATHENA NEWS ENGINE — PHASE 10.1 DETERMINISTIC TEST SUITE
 * Phase10_1_LiveIntelligenceActivation.test.ts
 * 
 * Verifies live intelligence activation, event-to-market-reaction pipeline,
 * market confirmation, incremental pulse & sector updates, Telegram immediate dispatch,
 * zero AI cost compliance, and non-fabrication of market data.
 */

import { LiveIntelligenceOrchestrator } from '../intelligence/LiveIntelligenceOrchestrator';
import { EventCentricOrchestrator } from '../intelligence/EventCentricOrchestrator';
import { MarketPulseEngine } from '../intelligence/MarketPulseEngine';
import { SectorIntelligenceEngine } from '../intelligence/SectorIntelligenceEngine';
import { MarketConfirmationEngine } from '../intelligence/MarketConfirmationEngine';
import { marketDataProviderManager } from '../market-data/MarketDataProvider';
import { TelegramNotificationPipeline } from '../telegram/TelegramNotificationPipeline';
import { TraderTelegramFormatter } from '../telegram/TraderTelegramFormatter';
import { JsonNewsStore } from '../storage/JsonNewsStore';
import { NewsArticle } from '../types/Article';

export async function runPhase10_1_Tests(): Promise<{ passed: boolean; results: Array<{ test: string; status: 'PASS' | 'FAIL'; error?: string }> }> {
  const results: Array<{ test: string; status: 'PASS' | 'FAIL'; error?: string }> = [];

  const logTest = (test: string, fn: () => void | Promise<void>) => {
    try {
      const res = fn();
      if (res && typeof (res as any).then === 'function') {
        return (res as any)
          .then(() => {
            results.push({ test, status: 'PASS' });
          })
          .catch((err: any) => {
            results.push({ test, status: 'FAIL', error: err.message });
          });
      } else {
        results.push({ test, status: 'PASS' });
      }
    } catch (err: any) {
      results.push({ test, status: 'FAIL', error: err.message });
    }
  };

  // Setup test environment
  marketDataProviderManager.setMode('TEST');
  LiveIntelligenceOrchestrator.resetInstance();
  EventCentricOrchestrator.resetInstance();
  const store = new JsonNewsStore();
  const liveOrchestrator = LiveIntelligenceOrchestrator.getInstance();

  // Test 1: Immediate Live Processing of Bullish Corporate Catalyst Article
  await logTest('1. Live Activation: Immediate Article -> Event Cluster -> Intelligence Pipeline', async () => {
    const article: Partial<NewsArticle> = {
      id: 'art_p10_1_001',
      headline: 'HDFC Bank wins major ₹12,000 crore government treasury mandate',
      body: 'HDFC Bank has been selected by the Finance Ministry for managing central treasury flows.',
      publishedAt: new Date().toISOString(),
      symbol: 'HDFCBANK',
      primaryCategory: 'CORPORATE'
    };

    const res = await liveOrchestrator.processArticle(article, store);
    if (!res.eventId) throw new Error('Event ID not generated by live orchestrator');
    if (res.symbol !== 'HDFCBANK') throw new Error(`Expected symbol HDFCBANK, got ${res.symbol}`);
    if (!res.marketConfirmation) throw new Error('Market confirmation dossier missing');
    if (res.telemetry.totalLatencyMs < 0) throw new Error('Invalid telemetry latency');
  });

  // Test 2: Contradiction Detection (Bullish News + Negative Price Reaction)
  await logTest('2. Market Confirmation: Contradiction Detection for Bullish News + Negative Stock Action', () => {
    const confirmation = MarketConfirmationEngine.process('HDFCBANK', new Date().toISOString(), 'BULLISH');
    // Price reaction in TEST mode might evaluate negative or neutral, test structure ensures logic holds
    if (confirmation.fundamentalDirection !== 'BULLISH') throw new Error('Fundamental direction mismatch');
    if (confirmation.contradictionFlags.length > 0) {
      if (confirmation.overallConfirmation !== 'CONTRADICTED') {
        throw new Error(`Expected CONTRADICTED state when flags present, got ${confirmation.overallConfirmation}`);
      }
    }
  });

  // Test 3: Multi-Publisher Event Clustering (Second Article for Same Event)
  await logTest('3. Event Clustering: Second Publisher Attached to Existing Cluster', async () => {
    const article2: Partial<NewsArticle> = {
      id: 'art_p10_1_002',
      headline: 'Finance Ministry awards ₹12,000 Cr treasury management deal to HDFC Bank',
      body: 'Official confirmation from Ministry of Finance regarding HDFC Bank treasury mandate.',
      publishedAt: new Date().toISOString(),
      symbol: 'HDFCBANK',
      primaryCategory: 'CORPORATE'
    };



    const res2 = await liveOrchestrator.processArticle(article2, store);
    if (res2.isNewEvent) throw new Error('Second article on same topic created duplicate event cluster');
    if (res2.eventRevision <= 1) throw new Error(`Event revision should increment, got ${res2.eventRevision}`);
  });

  // Test 4: Incremental Market Pulse Update
  await logTest('4. Market Pulse: Incremental Regime & High-Signal Drivers Update', async () => {
    const pulseEngine = MarketPulseEngine.getInstance();
    const pulse = await pulseEngine.getMarketPulse(store);
    if (!pulse.timestamp) throw new Error('Market pulse timestamp missing');
    if (!pulse.overallRegime) throw new Error('Market pulse overall regime missing');
    if (!Array.isArray(pulse.keyDrivers)) throw new Error('Market pulse key drivers array missing');
  });

  // Test 5: Incremental Sector Intelligence Update
  await logTest('5. Sector Intelligence: Dynamic Constituent & Event Timeline Update', async () => {
    const sectorEngine = SectorIntelligenceEngine.getInstance();
    const bankingIntel = await sectorEngine.getSectorIntelligence('BANKING', store);
    if (bankingIntel.sector !== 'BANKING') throw new Error(`Expected BANKING sector, got ${bankingIntel.sector}`);
    if (bankingIntel.topCompanies.length === 0) throw new Error('Banking top companies list empty');

    const hdfcComp = bankingIntel.topCompanies.find(c => c.symbol === 'HDFCBANK');
    if (!hdfcComp) throw new Error('HDFCBANK missing from BANKING sector top companies');
    if (hdfcComp.recentEventCount === 0) throw new Error('HDFCBANK event count not updated after processing article');
  });

  // Test 6: Sector Impact Boundary (Non-Sector Company Event)
  await logTest('6. Sector Boundaries: Non-Sector Symbol Returns NO_SECTOR_IMPACT', async () => {
    const sectorEngine = SectorIntelligenceEngine.getInstance();
    const event = EventCentricOrchestrator.getInstance().getAllEvents()[0];
    if (event) {
      const res = await sectorEngine.updateSectorIncremental('UNKNOWN_CORP_TICKER', event, store);
      if (res.impact !== 'NO_SECTOR_IMPACT') throw new Error(`Expected NO_SECTOR_IMPACT, got ${res.impact}`);
    }
  });

  // Test 7: Telegram Immediate Dispatch & Zero-Fabrication Enforcement
  await logTest('7. Telegram Dispatch: Immediate Dispatch & Non-Fabrication of Missing F&O Data', () => {
    const formatted = TraderTelegramFormatter.format({
      isEligible: true,
      companyName: 'HDFC Bank Ltd',
      symbol: 'HDFCBANK',
      eventType: 'ORDER_WIN',
      category: 'CORPORATE',
      direction: 'BULLISH',
      directionReason: 'Major government treasury mandate win.',
      score: 85,
      confidence: 90,
      urgency: 'HIGH',
      executiveSummary: 'HDFC Bank has been awarded a ₹12,000 crore treasury mandate.',
      whyItMatters: 'Substantial fee income and float deposit addition.',
      observedMarketReaction: 'Stock +1.4% with 2.1x volume surge.',
      traderRelevance: 'High interest for banking sector traders.',
      whatToMonitor: ['Treasury deposit inflows', 'RBI policy guidelines'],
      sources: ['Economic Times', 'NSE'],
      scoreBreakdown: {
        marketImpact: 20,
        eventSignificance: 18,
        fnoRelevance: 15,
        evidenceQuality: 15,
        entityRelevance: 10,
        sourceAuthority: 5,
        novelty: 2
      },
      fnoEvidence: {
        hasExplicitDerivativesData: false
      }
    });

    if (!formatted.includes('HDFC BANK LTD')) throw new Error('Formatted message title missing company name');
    if (!formatted.includes('Executive Summary')) throw new Error('Formatted message missing Executive Summary');
    if (formatted.includes('F&O Intelligence')) throw new Error('Telegram alert output empty/fabricated F&O section when derivatives data was false');
  });


  // Test 8: Live Telemetry & Latency Metric Collection
  await logTest('8. Observability: Live Telemetry & Latency Metrics Tracking', () => {
    const history = liveOrchestrator.getTelemetryHistory();
    if (history.length === 0) throw new Error('Telemetry history is empty');
    const last = history[history.length - 1];
    if (typeof last.totalLatencyMs !== 'number') throw new Error('Total latency metric missing from telemetry');
  });

  const allPassed = results.every(r => r.status === 'PASS');
  return { passed: allPassed, results };
}
