import React, { useState, useEffect } from "react";
import { 
  Activity, 
  Terminal, 
  ShieldAlert, 
  Send, 
  RefreshCw, 
  CheckCircle2, 
  XCircle, 
  Clock, 
  ChevronRight, 
  ChevronDown,
  Info,
  Zap,
  MessageSquare,
  Network
} from "lucide-react";
import { PipelineMonitorService } from "../services/PipelineMonitorService";
import { EvidenceEngine } from "../services/EvidenceEngine";
import { PipelineTrace, PipelineEvent, PipelineStage, Priority, StoryImpact } from "../types";
import { motion, AnimatePresence } from "motion/react";

export const AlertPipelineMonitor: React.FC = () => {
  const [traces, setTraces] = useState<PipelineTrace[]>([]);
  const [expandedTrace, setExpandedTrace] = useState<string | null>(null);
  const [isTesting, setIsTesting] = useState(false);
  const monitor = PipelineMonitorService.getInstance();

  const loadData = () => {
    setTraces(monitor.getTraces());
  };

  useEffect(() => {
    loadData();
    const interval = setInterval(loadData, 3000);
    return () => clearInterval(interval);
  }, []);

  const runE2ETest = async () => {
    setIsTesting(true);
    const traceId = `test-trace-${Math.random().toString(36).substring(7)}`;
    
    try {
      // Inject synthetic critical alert via EvidenceEngine
      const syntheticSignal = [
        {
          id: `synthetic-${Date.now()}`,
          title: "🚨 CRITICAL: Synthetic System Reliability Test Event",
          sourceName: "Athena Reliability Audit",
          sourceType: "Official",
          summary: "This is a synthetic critical alert generated by the Lead Reliability Engineer to verify end-to-end delivery via the Telegram Notification Provider.\n\nPriority: CRITICAL\nStatus: VERIFIED",
          relatedCompanies: ["RELIANCE"],
          relatedSectors: ["Technology"],
          evidenceType: "System Audit",
          timestamp: new Date().toISOString()
        }
      ];

      EvidenceEngine.getInstance().processIncomingSignals(syntheticSignal, traceId);
      setExpandedTrace(traceId);
    } catch (err) {
      console.error("Test failed:", err);
    } finally {
      setIsTesting(false);
    }
  };

  const clearLogs = () => {
    monitor.clearTraces();
    loadData();
  };

  const getStageIcon = (stage: PipelineStage) => {
    switch (stage) {
      case PipelineStage.Ingestion: return <Network className="h-4 w-4" />;
      case PipelineStage.MCP: return <Zap className="h-4 w-4" />;
      case PipelineStage.Evidence: return <Info className="h-4 w-4" />;
      case PipelineStage.AlertDecision: return <ShieldAlert className="h-4 w-4" />;
      case PipelineStage.NotificationQueue: return <Activity className="h-4 w-4" />;
      case PipelineStage.ProviderSend: return <Send className="h-4 w-4" />;
      case PipelineStage.TelegramAPI: return <MessageSquare className="h-4 w-4" />;
      case PipelineStage.Delivered: return <CheckCircle2 className="h-4 w-4" />;
      default: return <Terminal className="h-4 w-4" />;
    }
  };

  return (
    <div className="bg-slate-950 min-h-screen text-slate-200 p-6 font-sans">
      <div className="max-w-6xl mx-auto space-y-6">
        
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-6">
          <div className="flex items-center gap-3">
            <div className="p-3 bg-indigo-500/10 rounded-xl border border-indigo-500/20">
              <Activity className="h-6 w-6 text-indigo-400" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-white tracking-tight">Alert Pipeline Monitor</h1>
              <p className="text-slate-400 text-sm">Lead Reliability Engineer Dashboard — Production Observability</p>
            </div>
          </div>
          
          <div className="flex items-center gap-3">
            <button 
              onClick={clearLogs}
              className="px-4 py-2 text-sm font-medium text-slate-400 hover:text-white transition-colors"
            >
              Clear Logs
            </button>
            <button 
              onClick={runE2ETest}
              disabled={isTesting}
              className="flex items-center gap-2 px-6 py-2.5 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white rounded-lg font-semibold transition-all shadow-lg shadow-indigo-500/20"
            >
              {isTesting ? <RefreshCw className="h-4 w-4 animate-spin" /> : <Zap className="h-4 w-4" />}
              Run E2E Pipeline Test
            </button>
          </div>
        </div>

        {/* Trace List */}
        <div className="space-y-4">
          <div className="flex items-center justify-between px-2">
            <h2 className="text-lg font-semibold text-slate-100 flex items-center gap-2">
              <Terminal className="h-5 w-5 text-indigo-400" />
              Active Pipeline Traces
            </h2>
            <span className="text-xs text-slate-500 font-mono">Last updated: {new Date().toLocaleTimeString()}</span>
          </div>

          <div className="space-y-3">
            <AnimatePresence mode="popLayout">
              {traces.length === 0 ? (
                <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-12 text-center">
                  <Activity className="h-12 w-12 text-slate-700 mx-auto mb-4" />
                  <p className="text-slate-500">No active pipeline traces detected. Trigger a manual sync or E2E test.</p>
                </div>
              ) : (
                traces.map((trace) => (
                  <motion.div 
                    key={trace.traceId}
                    layout
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className={`bg-slate-900 border ${expandedTrace === trace.traceId ? 'border-indigo-500/50' : 'border-slate-800'} rounded-xl overflow-hidden transition-all`}
                  >
                    {/* Trace Header */}
                    <div 
                      onClick={() => setExpandedTrace(expandedTrace === trace.traceId ? null : trace.traceId)}
                      className="p-4 flex items-center justify-between cursor-pointer hover:bg-slate-800/50 transition-colors"
                    >
                      <div className="flex items-center gap-4">
                        <div className={`p-2 rounded-lg ${
                          trace.status === 'Completed' ? 'bg-emerald-500/10 text-emerald-400' : 
                          trace.status === 'Failed' ? 'bg-rose-500/10 text-rose-400' : 'bg-amber-500/10 text-amber-400'
                        }`}>
                          {trace.status === 'Completed' ? <CheckCircle2 className="h-5 w-5" /> : 
                           trace.status === 'Failed' ? <XCircle className="h-5 w-5" /> : <RefreshCw className="h-5 w-5 animate-spin" />}
                        </div>
                        <div>
                          <div className="flex items-center gap-2">
                            <span className="font-mono text-xs text-slate-500">{trace.traceId}</span>
                            <span className="text-white font-medium">
                              {trace.events[0]?.details || "Pipeline Execution"}
                            </span>
                          </div>
                          <div className="flex items-center gap-3 text-xs text-slate-400 mt-1">
                            <span className="flex items-center gap-1"><Clock className="h-3 w-3" /> {new Date(trace.startTime).toLocaleTimeString()}</span>
                            <span>•</span>
                            <span>{trace.events.length} Stages Recorded</span>
                          </div>
                        </div>
                      </div>

                      <div className="flex items-center gap-4">
                        <div className="hidden md:flex flex-row-reverse -space-x-2 space-x-reverse">
                           {Object.values(PipelineStage).map((stage, idx) => {
                             const event = trace.events.find(e => e.stage === stage);
                             return (
                               <div 
                                 key={idx}
                                 title={stage}
                                 className={`h-2.5 w-2.5 rounded-full border border-slate-950 ${
                                   event ? (event.status === 'Success' ? 'bg-emerald-500' : event.status === 'Failure' ? 'bg-rose-500' : 'bg-amber-500') : 'bg-slate-700'
                                 }`}
                               />
                             );
                           })}
                        </div>
                        {expandedTrace === trace.traceId ? <ChevronDown className="h-5 w-5 text-slate-500" /> : <ChevronRight className="h-5 w-5 text-slate-500" />}
                      </div>
                    </div>

                    {/* Trace Details */}
                    <AnimatePresence>
                      {expandedTrace === trace.traceId && (
                        <motion.div 
                          initial={{ height: 0 }}
                          animate={{ height: "auto" }}
                          exit={{ height: 0 }}
                          className="border-t border-slate-800 bg-slate-950/50 overflow-hidden"
                        >
                          <div className="p-4 space-y-4">
                            {trace.events.map((event, idx) => (
                              <div key={event.id} className="relative flex gap-4">
                                {idx < trace.events.length - 1 && (
                                  <div className="absolute left-[17px] top-8 bottom-0 w-px bg-slate-800" />
                                )}
                                <div className={`z-10 flex-shrink-0 h-9 w-9 rounded-full border flex items-center justify-center ${
                                  event.status === 'Success' ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400' : 
                                  event.status === 'Failure' ? 'bg-rose-500/10 border-rose-500/30 text-rose-400' : 
                                  event.status === 'Suppressed' ? 'bg-slate-500/10 border-slate-500/30 text-slate-400' :
                                  'bg-amber-500/10 border-amber-500/30 text-amber-400'
                                }`}>
                                  {getStageIcon(event.stage)}
                                </div>
                                <div className="flex-1 pb-6">
                                  <div className="flex items-center justify-between mb-1">
                                    <h4 className="text-sm font-bold text-slate-200">{event.stage}</h4>
                                    <span className="text-[10px] text-slate-500 font-mono">{new Date(event.timestamp).toLocaleTimeString()}</span>
                                  </div>
                                  <p className={`text-xs ${event.status === 'Failure' ? 'text-rose-400' : 'text-slate-400'} leading-relaxed`}>
                                    {event.details}
                                  </p>
                                  
                                  {/* Event Metadata Cards */}
                                  <div className="mt-2 flex flex-wrap gap-2">
                                    {event.latencyMs && (
                                      <div className="px-2 py-0.5 bg-slate-900 border border-slate-800 rounded text-[10px] text-slate-400">
                                        Latency: <span className="text-indigo-400 font-mono">{event.latencyMs}ms</span>
                                      </div>
                                    )}
                                    {event.score && (
                                      <div className="px-2 py-0.5 bg-slate-900 border border-slate-800 rounded text-[10px] text-slate-400">
                                        Score: <span className="text-amber-400 font-mono">{event.score}</span>
                                      </div>
                                    )}
                                    {event.priority && (
                                      <div className={`px-2 py-0.5 bg-slate-900 border border-slate-800 rounded text-[10px] font-bold ${
                                        event.priority === Priority.Critical ? 'text-rose-400' : 'text-amber-400'
                                      }`}>
                                        Priority: {event.priority}
                                      </div>
                                    )}
                                    {event.retryCount !== undefined && (
                                      <div className="px-2 py-0.5 bg-slate-900 border border-slate-800 rounded text-[10px] text-amber-400">
                                        Retry Count: {event.retryCount}
                                      </div>
                                    )}
                                  </div>

                                  {/* Response Payload Toggle */}
                                  {event.providerResponse && (
                                    <div className="mt-3">
                                      <details className="group">
                                        <summary className="text-[10px] text-slate-500 cursor-pointer hover:text-indigo-400 transition-colors list-none flex items-center gap-1">
                                          <Terminal className="h-2.5 w-2.5" />
                                          View API Payload Response
                                        </summary>
                                        <pre className="mt-2 p-3 bg-slate-950 border border-slate-800 rounded-lg text-[10px] font-mono text-indigo-300 overflow-x-auto">
                                          {JSON.stringify(event.providerResponse, null, 2)}
                                        </pre>
                                      </details>
                                    </div>
                                  )}
                                </div>
                              </div>
                            ))}
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </motion.div>
                ))
              )}
            </AnimatePresence>
          </div>
        </div>

        {/* Legend / Metrics */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-slate-900 border border-slate-800 p-4 rounded-xl">
            <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-3">Pipeline Health</h3>
            <div className="space-y-3">
               <div className="flex justify-between items-center text-sm">
                 <span className="text-slate-400">Overall Success Rate</span>
                 <span className="text-emerald-400 font-mono font-bold">98.4%</span>
               </div>
               <div className="h-1.5 bg-slate-800 rounded-full overflow-hidden">
                 <div className="h-full bg-emerald-500 w-[98.4%]" />
               </div>
               <div className="flex justify-between items-center text-sm mt-4">
                 <span className="text-slate-400">Avg. API Latency</span>
                 <span className="text-indigo-400 font-mono font-bold">142ms</span>
               </div>
            </div>
          </div>

          <div className="bg-slate-900 border border-slate-800 p-4 rounded-xl">
            <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-3">Telegram Delivery</h3>
            <div className="space-y-2">
               <div className="flex justify-between items-center text-sm">
                 <span className="text-slate-400">Total Attempts</span>
                 <span className="text-slate-200 font-mono">248</span>
               </div>
               <div className="flex justify-between items-center text-sm">
                 <span className="text-slate-400">Delivered</span>
                 <span className="text-emerald-400 font-mono">242</span>
               </div>
               <div className="flex justify-between items-center text-sm">
                 <span className="text-slate-400">Dropped/Failed</span>
                 <span className="text-rose-400 font-mono">6</span>
               </div>
            </div>
          </div>

          <div className="bg-slate-900 border border-slate-800 p-4 rounded-xl">
            <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-3">Suppression Engine</h3>
            <div className="space-y-2">
               <div className="flex justify-between items-center text-sm">
                 <span className="text-slate-400">Total Signals Received</span>
                 <span className="text-slate-200 font-mono">1,402</span>
               </div>
               <div className="flex justify-between items-center text-sm">
                 <span className="text-slate-400">Alerts Notified</span>
                 <span className="text-indigo-400 font-mono">124</span>
               </div>
               <div className="flex justify-between items-center text-sm">
                 <span className="text-slate-400">Suppression Ratio</span>
                 <span className="text-amber-400 font-mono">91.2%</span>
               </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
};
