/**
 * ATHENA NEWS ENGINE — ADAPTIVE SUMMARY SUITE
 * EvidenceMap
 * 
 * Defines the structured Evidence Map generated by full-article traversal.
 * Represents all grounded facts, multi-entity matrices, section occurrences,
 * and key quantitative figures extracted across the entire source document.
 */

import { SemanticArticleType } from './ArticleTypeClassifier.ts';
import { StructuredKeyNumber } from '../types/CanonicalSchema.ts';

export type ArticleSection = 
  | 'HEADLINE'
  | 'LEAD'
  | 'EARLY_BODY'
  | 'MIDDLE_BODY'
  | 'LATE_BODY'
  | 'CONCLUSION';

export type CoverageScope = 
  | 'SINGLE_ENTITY'
  | 'MULTI_ENTITY_COMPARISON'
  | 'MARKET_THEMATIC';

export interface EntityFactItem {
  entityName: string;
  gmp?: string;
  estListingPrice?: string;
  estListingPremium?: string;
  subscription?: string;
  priceBand?: string;
  issueSize?: string;
  orderValue?: string;
  revenue?: string;
  netProfit?: string;
  margin?: string;
  actionOrStatus?: string;
  keySentence?: string;
  rawMetrics: StructuredKeyNumber[];
}

export interface SectionFact {
  section: ArticleSection;
  text: string;
  numbers: StructuredKeyNumber[];
  entities: string[];
}

export interface EvidenceMap {
  headline: string;
  articleType: SemanticArticleType;
  coverageScope: CoverageScope;
  entities: string[];
  entityFactMatrix: EntityFactItem[];
  sectionFacts: SectionFact[];
  structuredNumbers: StructuredKeyNumber[];
  primaryEvent: string;
  macroCatalysts: string[];
  technicalLevels: string[];
  companyResponses: string[];
  marketReactions: string[];
  uncertaintyPhrases: string[];
  sectionPresence: {
    lead: boolean;
    middle: boolean;
    late: boolean;
    conclusion: boolean;
  };
  totalExtractedFactsCount: number;
}
