import { NewsArticleV2 } from "../domain/NewsArticle.ts";
import { NormalizedFinancialMetric } from "../intelligence/FinancialMetricEngine.ts";
import { UnifiedIntelligenceEngine } from "../intelligenceV2/UnifiedIntelligenceEngine.ts";

export interface NewsSummary {
  summary: string;
  whatChanged: string[];
  keyMetrics: NormalizedFinancialMetric[];
  whyItMatters: string;
  marketImpact: string;
  riskWatchpoints: string[];
  confidence: number;
  processingMode: "DETERMINISTIC" | "AI_GROUNDED" | "DETERMINISTIC_FALLBACK";
  sourceGrounded: boolean;
}

export class SummaryEngine {
  /**
   * Generates a source-grounded structured summary synchronously for a News Core V2 article
   * backed by the canonical UnifiedIntelligenceEngine.
   */
  public static generateDeterministicSummarySync(article: NewsArticleV2): NewsSummary {
    const intel = UnifiedIntelligenceEngine.build(article);

    const keyMetrics: NormalizedFinancialMetric[] = intel.financialMetrics.map(m => {
      let metricName: NormalizedFinancialMetric["metricName"] = "PAT";
      if (m.name === "Revenue") metricName = "Revenue";
      else if (m.name === "EBITDA") metricName = "EBITDA";
      else if (m.name === "EBITDA Margin" || m.name === "Margin") metricName = "EBITDA Margin";
      else if (m.name === "EPS") metricName = "EPS";
      else if (m.name === "NII") metricName = "NII";
      else if (m.name === "Debt") metricName = "Debt";
      else if (m.name === "Order Book") metricName = "Order Book";

      return {
        metricName,
        currentValue: m.currentValue,
        previousValue: m.previousValue,
        change: m.change,
        changePercent: m.changePercent,
        direction: m.direction,
        unit: m.unit,
        sourceSentence: m.sourceSentence || "",
        displayText: m.displayText
      };
    });

    return {
      summary: intel.executiveSummary,
      whatChanged: intel.keyFacts,
      keyMetrics,
      whyItMatters: intel.whyItMatters,
      marketImpact: intel.optionsSellerImpact || intel.marketImpact,
      riskWatchpoints: intel.risk,
      confidence: intel.materialityScore,
      processingMode: "DETERMINISTIC",
      sourceGrounded: true,
    };
  }

  /**
   * Generates a source-grounded structured summary for a News Core V2 article
   * backed by the canonical UnifiedIntelligenceEngine.
   */
  public static async generateSummary(article: NewsArticleV2): Promise<NewsSummary> {
    const intel = await UnifiedIntelligenceEngine.generateAIIntelligence(article);
    const deterministic = this.generateDeterministicSummarySync(article);
    
    // Merge
    return {
      ...deterministic,
      summary: intel.executiveSummary,
      whyItMatters: intel.whyItMatters,
      marketImpact: intel.marketImpact,
      riskWatchpoints: intel.risk,
      // determine if it's AI generated by checking version
      processingMode: intel.intelligenceVersion.includes("_AI") ? "AI_GROUNDED" : "DETERMINISTIC_FALLBACK"
    };
  }
}
