export interface FactVerificationResult {
  verifiedFacts: string[];
  unverifiedClaimsRemoved: number;
  hasSufficientEvidence: boolean;
  status: 'VERIFIED' | 'PARTIALLY_VERIFIED' | 'INSUFFICIENT_INFORMATION';
}

export class HallucinationGuard {
  /**
   * Validates facts extracted or generated by AI against the ground-truth article title, body, and metadata.
   */
  public static verifyFacts(
    claims: string[],
    sourceTitle: string,
    sourceBody: string
  ): FactVerificationResult {
    const combinedSource = `${sourceTitle} ${sourceBody}`.toLowerCase();
    const verifiedFacts: string[] = [];
    let unverifiedCount = 0;

    for (const claim of claims) {
      if (!claim || claim.trim().length === 0) continue;

      const claimLower = claim.toLowerCase();

      // Check if numbers/percentages in claim exist in source text
      const numbersInClaim = claimLower.match(/\b\d+(\.\d+)?%?\b/g) || [];
      let numbersMatch = true;

      for (const num of numbersInClaim) {
        // Ignore single digits or years like 2025/2026
        if (num.length <= 1 || num === '2025' || num === '2026') continue;
        if (!combinedSource.includes(num)) {
          numbersMatch = false;
          break;
        }
      }

      if (numbersMatch) {
        verifiedFacts.push(claim.trim());
      } else {
        unverifiedCount++;
      }
    }

    if (verifiedFacts.length === 0) {
      return {
        verifiedFacts: ['Insufficient verified information.'],
        unverifiedClaimsRemoved: unverifiedCount,
        hasSufficientEvidence: false,
        status: 'INSUFFICIENT_INFORMATION',
      };
    }

    return {
      verifiedFacts,
      unverifiedClaimsRemoved: unverifiedCount,
      hasSufficientEvidence: true,
      status: unverifiedCount === 0 ? 'VERIFIED' : 'PARTIALLY_VERIFIED',
    };
  }
}
